[package]
namespace   = "mcpplibs"
name        = "xpkg"
version     = "0.0.58"
description = "C++23 reference implementation of the xpkg V2 spec (multi-arch)"
license     = "Apache-2.0"
repo        = "https://github.com/openxlings/libxpkg"

[targets.xpkg]
kind = "lib"

[dependencies]
"mcpplibs.capi.lua" = "0.0.3"

[dev-dependencies]
gtest = "1.15.2"
